services:
  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "${APP_URL}" 
      APP_SECRET: "${APP_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
      REDIS_URL: "${REDIS_URL}"
      MAIL_DRIVER: "${MAIL_DRIVER}" 
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}" 
      SMTP_USERNAME: "${SMTP_USERNAME}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_SECURE: "${SMTP_SECURE}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME}"
    expose:
      - "3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage
    networks:
      - caddy_network
      - docmost

  db:
    image: postgres:16-alpine
    container_name: docmost-db 
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: unless-stopped
    networks:
      - docmost
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    container_name: docmost-redis
    image: redis:7.2-alpine
    restart: unless-stopped
    networks:
      - docmost
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:

networks:
  docmost:
    driver: bridge
  caddy_network:
    external: true
