services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-app
    expose:
      - "5678"
    environment:
      - N8N_HOST=n8n.yasasvi.site
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_TUNNEL_URL=https://n8n.yasasvi.site
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always
    networks:
      - caddy_network
volumes:
  n8n_data:
networks:
  caddy_network:
    external: true
